Core_Portfolio_Project/Core_Portfolio_Project/Controllers/FeatureController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core_Portfolio_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeatureController : Controller
    {
        private readonly FeatureManager featureManager;

        private readonly IValidator<Feature> _validator;

        public FeatureController(FeatureManager featureManager, IValidator<Feature> validator)
        {
            this.featureManager = featureManager;
            _validator = validator;
        }
        public IActionResult Index()
        {
            ViewBag.v1 = "Öne Çıkanlar";
            ViewBag.v2 = "Öne Çıkan Sayfası";
            var values = featureManager.GetByID(1);
            return View(values);
        }

        [HttpPost]

        public IActionResult EditFeature(Feature feature)
        {
            var result = _validator.Validate(feature);

            if (result.IsValid)
            {
                featureManager.TUpdate(feature);
                return RedirectToAction("Index", "Default");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }

            return View(feature);
        }
    }
}

Core_Portfolio_Project/Core_Portfolio_Project/Views/Feature/Index.cshtml
@model EntityLayer.Concrete.Feature
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("EditFeature", "Feature", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Feature Düzenleme Paneli </p>

                @Html.HiddenFor(x => x.FeatureID)

                <div class="form-group">
                    <label>Başlık</label>
                    @Html.TextBoxFor(x => x.Header, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Header, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label>Ad Soyad</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label>Ünvan</label>
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Title, "", new { @class = "text-danger" })
                </div>

                <button type="submit" class="btn btn-primary mr-2">Güncelle</button>
                <a href="@Url.Action("Index", "Feature")" class="btn btn-dark">İptal</a>
            </div>
        </div>
    </div>
}